services:
  train_orchestrator:
    build:
      context: .
      dockerfile: ./Dockerfile_sncf_orchestrator
    container_name: train_orchestrator
    image: train_orchestrator_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: '${DAGSTER_POSTGRES_USER}'
      DAGSTER_POSTGRES_PASSWORD: '${DAGSTER_POSTGRES_PASSWORD}'
      DAGSTER_POSTGRES_DB: '${DAGSTER_POSTGRES_DB}'
      DAGSTER_POSTGRES_HOST: '${DAGSTER_POSTGRES_HOST}'
      DAGSTER_CURRENT_IMAGE: 'train_orchestrator_image'
      S3_API: '${S3_API}'
      S3_ACCESS_KEY: '${S3_ACCESS_KEY}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      REGION_NAME: '${REGION_NAME}'
      BUCKET_NAME: '${BUCKET_NAME}'
    networks:
      - dagster_network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 4000), timeout=3)"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  dagster_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '3000'
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    ports:
      - '3000:3000'
    environment:
      DAGSTER_POSTGRES_USER: '${DAGSTER_POSTGRES_USER}'
      DAGSTER_POSTGRES_PASSWORD: '${DAGSTER_POSTGRES_PASSWORD}'
      DAGSTER_POSTGRES_DB: '${DAGSTER_POSTGRES_DB}'
      DAGSTER_POSTGRES_HOST: '${DAGSTER_POSTGRES_HOST}'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      train_orchestrator:
        condition: service_healthy

  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: '${DAGSTER_POSTGRES_USER}'
      DAGSTER_POSTGRES_PASSWORD: '${DAGSTER_POSTGRES_PASSWORD}'
      DAGSTER_POSTGRES_DB: '${DAGSTER_POSTGRES_DB}'
      DAGSTER_POSTGRES_HOST: '${DAGSTER_POSTGRES_HOST}'
      S3_API: '${S3_API}'
      S3_ACCESS_KEY: '${S3_ACCESS_KEY}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      REGION_NAME: '${REGION_NAME}'
      BUCKET_NAME: '${BUCKET_NAME}'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_network
    depends_on:
      train_orchestrator:
        condition: service_healthy

networks:
  dagster_network:
    driver: bridge
    name: dagster_network