[project]
name = "train-flow-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.97",
    "dagster>=1.13.1",
    "dagster-dg-cli>=1.13.1",
    "dagster-webserver>=1.13.1",
    "data-eng",
    "dbt-core>=1.11.11",
    "dbt-duckdb>=1.10.1",
    "duckdb>=1.5.4",
    "gtfs-kit>=12.0.3",
    "gtfs-realtime-bindings>=2.0.0",
    "minio>=7.2.20",
    "numpy>=2.4.4",
    "polars>=1.40.1",
    "pre-commit>=4.6.0",
    "protobuf-decoder>=0.4.0",
    "ruff>=0.15.12",
]

[tool.uv.workspace]
members = [
    "data-eng",
]

[tool.uv.sources]
data-eng = { workspace = true }

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "data-eng.src.data_eng.dagster"
code_location_target_module = "data_eng.dagster.defs.definitions"
