[project]
name = "train-flow-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "data-eng",
    "data-viz-platform",
    "orchestration-dagster",
    "pre-commit>=4.6.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.12",
]

[tool.uv.workspace]
members = [
    "data-eng",
    "data-viz-platform",
    "orchestration-dagster"
]

[tool.uv.sources]
data-eng = { workspace = true }
data-viz-platform = { workspace = true }
orchestration-dagster = { workspace = true }


[tool.ruff.lint]
# Règles à activer
select = [
    "E",      # Erreurs de style pycodestyle
    "F",      # Erreurs Pyflakes (variables non utilisées, etc.)
    "I",      # Tri des imports (isort)
    "B",      # Bugs potentiels (flake8-bugbear)
    "UP",     # Modernisation syntaxe (pyupgrade)
    "SIM",    # Simplifications possibles,
    "D",      # Doctrings manquantes ou mal formatées
]

# Règles à ignorer
ignore = [
    "E501",   # Ligne trop longue (géré par le formatter)
    "D203",
    "D213",
    "D100", 
    "D104"
]

# Règles que --fix peut corriger automatiquement
fixable = ["ALL"]

[tool.ruff.format]
# Style des guillemets (comme Black)
quote-style = "double"

# Indentation (comme Black)
indent-style = "space"

[dependency-groups]
dev = [
    "moto[s3]>=5.2.2",
    "pytest>=9.1.1",
]

[tool.ruff.lint.per-file-ignores]
"scripts/*" = ["D"]
