[project]
name = "train-flow-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "data-eng",
    "data-viz-platform",
    "orchestration-dagster",
    "pre-commit>=4.6.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.12",
    "streamlit>=1.60.0",
]

[tool.uv.workspace]
members = [
    "data-eng",
    "data-viz-platform",
    "orchestration-dagster"
]

[tool.uv.sources]
data-eng = { workspace = true }
data-viz-platform = { workspace = true }
orchestration-dagster = { workspace = true }
