sncf_data_analysis:
  target: dev
  outputs: 
    dev:
      type: duckdb
      path: "warehouse/sncf_data_analysis.duckdb"

      extensions:
        - httpfs

      settings:
        s3_endpoint: "127.0.0.1:9000"
        s3_url_style: "path"
        s3_use_ssl: false
        s3_region: "eu-west-1"
        s3_access_key_id: "{{ env_var('MINIO_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('MINIO_SECRET_ACCESS_KEY') }}"