[project]
name = "data-viz-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Baptiste Darnala", email = "darnala.b@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.61.1",
]

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"
